#!/usr/bin/env ruby
require_relative 'config/config.rb'
require_relative 'model/coding_activity'

Config.load
client = WakatimeClient.new
summaries = client.populate_summaries
CodingActivity.save_response(summaries)
